AY2122S2-CS2103T-T13-2/tp

docs/AboutUs.md
docs/index.md

Commits:
Update Index.md to reflect TAssist
Fix faulty link in AboutUs.md

Minor updates to adapt changes

---

docs/AboutUs.md
docs/UserGuide.md
docs/team/wxliong.md

* Update AboutUs page
* Update User Guide for add command
* Update PPP
* Fix #15

Update project website

---

docs/team/lkldev.md

Branch docs

---

docs/DeveloperGuide.md

Update DG with uses cases for Class Group

---

docs/DeveloperGuide.md

Update DG to include use cases for user interactions with Module

---

docs/DeveloperGuide.md

Update NFR and Glossary in DeveloperGuide

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/model/EntityType.java
src/main/java/seedu/address/model/module/Module.java
src/main/java/seedu/address/model/module/ModuleCode.java
src/main/java/seedu/address/model/module/ModuleName.java
src/main/java/seedu/address/model/module/UniqueModuleList.java
src/main/java/seedu/address/model/module/exceptions/DuplicateModuleException.java
src/main/java/seedu/address/model/module/exceptions/ModuleNotFoundException.java

Create UniqueModuleList to contain list of modules
Update Guides to remove trailing spaces flag by travis
Add enums of EntityTypes
Closes #43

Create Module entity and its attributes

---

src/main/java/seedu/address/model/student/Email.java
src/main/java/seedu/address/model/student/Name.java
src/main/java/seedu/address/model/student/NameContainsKeywordsPredicate.java
src/main/java/seedu/address/model/student/Phone.java
src/main/java/seedu/address/model/student/Student.java
src/main/java/seedu/address/model/student/StudentID.java
src/main/java/seedu/address/model/student/UniqueStudentList.java
src/main/java/seedu/address/model/student/exceptions/DuplicateStudentException.java
src/main/java/seedu/address/model/student/exceptions/StudentNotFoundException.java

Create model classes for Student, its attributes and UniqueStudentList

---

src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/model/classgroup/ClassGroupIdTest.java
src/test/java/seedu/address/model/classgroup/ClassGroupTest.java
src/test/java/seedu/address/model/classgroup/UniqueClassGroupListTest.java
src/test/java/seedu/address/testutil/ClassGroupBuilder.java
src/test/java/seedu/address/testutil/TypicalClassGroups.java

Add tests for ClassGroup, ClassGroupId and UniqueClassGroupList

---

docs/DeveloperGuide.md
docs/UserGuide.md

Update ACADEMIC_YEAR for Module and types for ClassGroup in UG

---

src/main/java/seedu/address/model/tamodule/AcademicYear.java
src/main/java/seedu/address/model/tamodule/TaModule.java

The field comes with a toStringInFull() method, which will return the academic year as a full string. 
E.g. input "21S1" will return the string "2021/2022 Semester 1".

Add AcademicYear field to TaModule

---

src/main/java/seedu/address/model/classgroup/ClassGroup.java
src/main/java/seedu/address/model/classgroup/ClassGroupType.java

ClassGroup class : toString() prints Module's academic year as well

Add toString() to ClassGroupType

---

docs/UserGuide.md

Update documentation for Academic Year in UG

---

src/main/java/seedu/address/storage/JsonAdaptedTaModule.java

Create JsonAdaptedTaModule for storage component

---

src/main/java/seedu/address/storage/JsonAdaptedStudent.java

Create JsonAdaptedStudent for storage component

---

src/main/java/seedu/address/storage/JsonAdaptedClassGroup.java

Add storage for ClassGroup

---

src/test/java/seedu/address/testutil/ClassGroupBuilder.java
src/test/java/seedu/address/testutil/ModuleBuilder.java
src/test/java/seedu/address/testutil/StudentBuilder.java
src/test/java/seedu/address/testutil/TAssistBuilder.java
src/test/java/seedu/address/testutil/TypicalClassGroups.java
src/test/java/seedu/address/testutil/TypicalModules.java
src/test/java/seedu/address/testutil/TypicalStudents.java
src/test/java/seedu/address/testutil/TypicalTAssist.java

Add helper classes for common class tests. Splitting #62  into smaller PRs that are more manageable.
These files should not affect any existing classes or app functionality.

Add utils for common class tests (related to issue #62)

---

src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/MarkCommand.java
src/main/java/seedu/address/logic/commands/UnmarkCommand.java
src/main/java/seedu/address/logic/parser/TAssistParser.java

Updated List command for Gernene to work on her v1.3, Created mark and unmark command for Andy to work on his v1.3

Update attributes of List command, add Mark and Unmark command

---

src/main/java/seedu/address/model/classgroup/ClassGroup.java
src/main/java/seedu/address/model/classgroup/ClassGroupId.java
src/main/java/seedu/address/model/classgroup/ClassGroupType.java
src/main/java/seedu/address/model/classgroup/UniqueClassGroupList.java
src/main/java/seedu/address/model/classgroup/exceptions/ClassGroupNotFoundException.java
src/main/java/seedu/address/model/classgroup/exceptions/DuplicateClassGroupException.java
src/main/java/seedu/address/model/lesson/Lesson.java
src/main/java/seedu/address/model/lesson/WeekId.java
src/main/java/seedu/address/model/studentattendance/Attendance.java
src/main/java/seedu/address/model/studentattendance/StudentAttendance.java

Add Lesson and StudentAttendance as well as author tags

---

src/main/java/seedu/address/ui/MainWindow.java

Fixes issue where multiple tabs are "active" if a user double-clicks one tab and then clicks another.

Fix ui tabs

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyTAssist.java
src/main/java/seedu/address/model/TAssist.java
src/main/java/seedu/address/model/assessment/Assessment.java
src/main/java/seedu/address/model/assessment/AssessmentName.java
src/main/java/seedu/address/model/assessment/Grade.java
src/main/java/seedu/address/model/assessment/SimpleName.java
src/main/java/seedu/address/model/assessment/UniqueAssessmentList.java
src/main/java/seedu/address/model/assessment/exceptions/AssessmentNotFoundException.java
src/main/java/seedu/address/model/assessment/exceptions/DuplicateAssessmentException.java
src/main/java/seedu/address/model/entity/EntityConverter.java
src/main/java/seedu/address/model/entity/EntityType.java
src/main/java/seedu/address/model/tamodule/TaModule.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/test/java/seedu/address/testutil/PersonBuilder.java

closes #116 
This PR creates the assessment entity and update the code to support this new entity. 
modifications made:
* Update parser to parse assessment entity
* Update Add, Delete and List command to support assessment entity
* Update SampleDataUtil to create sample assessments
Todos:
* update UI to support assessment entity
* update storage to save assessments

Creates assessment entity

---

src/main/java/seedu/address/logic/commands/DisenrolCommand.java
src/main/java/seedu/address/logic/commands/EditAB3Command.java
src/main/java/seedu/address/logic/commands/EnrolCommand.java
src/main/java/seedu/address/logic/commands/FindAB3Command.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/GradeCommand.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/TAssist.java
src/main/java/seedu/address/model/assessment/Assessment.java
src/main/java/seedu/address/model/student/UniqueStudentList.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditAB3CommandTest.java
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/commands/FindAB3CommandTest.java
src/test/java/seedu/address/logic/parser/FindAB3CommandParserTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java

Add methods to model, model manager, tassist and unique student list to help when parsing indexes and student IDs into a list of student objects
Added template for tassist commands that have yet to be created. This will allow those working on the commands to come up with the logic, while at the same time the person doing parsing will be able to create the commands.

Update common classes to facilitate collaboration among team members

---

docs/UserGuide.md

Add find feature to UG

---

src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/classgroup/ClassGroup.java
src/main/java/seedu/address/model/tamodule/TaModule.java

Update common classes to support getting the unfiltered lists
Update Module and ClassGroup to contain a list of students
Note: 
Storage needs to be updated to keep the list of students for class groups and modules

Update common classes

---

src/main/java/seedu/address/logic/commands/DisenrolCommand.java
src/main/java/seedu/address/logic/commands/EnrolCommand.java
src/main/java/seedu/address/logic/commands/GradeCommand.java
src/main/java/seedu/address/logic/commands/MarkCommand.java
src/main/java/seedu/address/logic/commands/UnmarkCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/MarkCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/TAssistParser.java
src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java

Closes #135 
* All instances of `isAllStudents` have been removed.
* Change `Optional<List<Student>>` to `List<Student>`.
To be merged only after #139 is merged.

Add parsing for mark and unmark command

---

src/main/java/seedu/address/logic/commands/ListCommand.java

This PR adds filtering capabilities to the list command. Please note that some of the methods used in this code may not exist yet.

Add filtering to list command logic

---

src/main/java/seedu/address/logic/commands/MarkCommand.java
src/main/java/seedu/address/logic/commands/UnmarkCommand.java
src/main/java/seedu/address/model/classgroup/ClassGroup.java
src/main/java/seedu/address/model/lesson/Lesson.java
src/main/java/seedu/address/model/lesson/WeekId.java
src/main/java/seedu/address/model/studentattendance/Attendance.java
src/main/java/seedu/address/model/studentattendance/StudentAttendance.java

Add mark/unmark feature

---

src/main/java/seedu/address/logic/commands/DisenrolCommand.java
src/main/java/seedu/address/logic/commands/GradeCommand.java
src/main/java/seedu/address/logic/commands/MarkCommand.java
src/main/java/seedu/address/logic/commands/UnmarkCommand.java
src/main/java/seedu/address/logic/parser/GradeCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/TAssist.java
src/main/java/seedu/address/model/assessment/Assessment.java
src/main/java/seedu/address/model/lesson/Lesson.java
src/main/java/seedu/address/model/studentattendance/Attendance.java
src/main/java/seedu/address/model/studentattendance/StudentAttendance.java
src/main/java/seedu/address/model/tamodule/TaModule.java
src/main/java/seedu/address/storage/JsonAdaptedClassGroup.java
src/main/java/seedu/address/storage/JsonAdaptedStudentAttendance.java
src/main/java/seedu/address/storage/JsonAdaptedTaModule.java

* Fixed bugs with storage for different entities
* Fixed disenrol command not deleting assessment
* Fixed mark and unmark command

Fix misc bugs

---

src/main/java/seedu/address/logic/commands/DisenrolCommand.java
src/main/java/seedu/address/logic/parser/GenericEnrolCommandParser.java
src/main/java/seedu/address/logic/parser/GradeCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/TAssist.java
src/main/resources/view/AttendanceWindow.fxml
src/main/resources/view/ClassGroupListCard.fxml

More bug fixes

---

docs/UserGuide.md
docs/_config.yml

Using the team branch-docs so that anybody can edit this PR
you can view the edits [here](https://lkldev.github.io/tp/UserGuide.html)

Update UG on format list/filter and add caution to delete

---

src/main/java/seedu/address/logic/commands/DisenrolCommand.java
src/main/java/seedu/address/logic/commands/EnrolCommand.java
src/main/java/seedu/address/model/student/Email.java
src/main/java/seedu/address/model/student/Name.java
src/main/java/seedu/address/model/student/StudentId.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

- Update INVALID_NAME in ParserUtilTest to pass Gradle
- Fixes #174 
- Fixes #180 
- Fixes #182 
- Fixes #199 
- Fixes #207

Fix PE-D bugs

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/GradeCommand.java
src/main/java/seedu/address/logic/parser/ListCommandParser.java
src/main/java/seedu/address/model/assessment/Assessment.java
src/main/java/seedu/address/model/assessment/Grade.java
src/main/java/seedu/address/model/tamodule/ModuleCode.java
src/main/java/seedu/address/model/tamodule/ModuleName.java

* Fixes #170
* Fixes #172  
* Fixes #176 
* Fixes #198
* Minor Bug fix in assessment not checking simple name and module to determine if assessment is unique

PE-D Bug fixes

---

src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/TAssist.java

Create method to check if student exists using studentId
